#!/bin/bash -ex
yum install epel-release -y
yum update -y
yum install docker distgen -y

systemctl enable --now docker

image='docker.io/slavek/distgen'
DG_BINARY_ARGS="docker run -v /run/docker.sock:/run/docker.sock -v $(pwd):/var/dgdir:Z $image"
docker pull $image

mkdir -p root/
make DG_BINARY="$DG_BINARY_ARGS" VARIANT=centos DISTRO=centos-7-x86_64 source
sudo chown -R $(id -u) .
