#!/bin/bash -ex

image='docker.io/slavek/distgen'
docker pull $image

mkdir -p root/
make DG_BINARY="docker run -v $(pwd):/var/dgdir $image" source
# A hack: we need Dockerhub to see a `Dockerfile` when cloning,
# but `Dockerfile` is actually a template and `make` will output
# `Dockerfile.rendered`. To make sure the build doesn't use
# the template, we replace it with the rendered `Dockerfile`
# after rendering.
sudo chown -R $(id -u) .
cp -a Dockerfile Dockerfile.template
